pipeline:
    name: Y2Mp3
    identifier: Y2Mp3
    projectIdentifier: _mansong
    orgIdentifier: default
    description: A simple desktop application to download Youtube videos to video (mp4, mpg, wmv) and audio (wav, flac, m4a, wma, mp3, ogg, acc) formats, one by one or all of them.
    tags:
        electronjs: ""
        nodejs: ""
        audio: ""
        download-audio: ""
        webpack: ""
    properties:
        ci:
            codebase:
                connectorRef: mansonggithub
                repoName: improved-happiness
                build: <+input>
    stages:
        - stage:
              name: Build and Publish
              identifier: Build_and_Publish
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: mansonggke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: Restore Cache
                                identifier: Restore_Cache
                                spec:
                                    connectorRef: mansongaws
                                    region: eu-west-2
                                    bucket: mansong-npm
                                    key: gesturerecognition
                                    archiveFormat: Tar
                                failureStrategies: []
                          - parallel:
                                - step:
                                      type: Run
                                      name: DockerLint
                                      identifier: DockerLint
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: hadolint/hadolint:latest-alpine
                                          command: |-
                                              hadolint Dockerfile.prod
                                              hadolint Dockerfile.dev
                                          privileged: false
                                - step:
                                      type: Run
                                      name: ESLint
                                      identifier: ESLint
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: pipelinecomponents/eslint
                                          command: eslint .
                                          privileged: false
                          - step:
                                type: Run
                                name: Install Dependencies
                                identifier: Install_Dependencies
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+Build_and_Publish.variables.node_version>
                                    command: npm install
                                    privileged: false
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                          - step:
                                type: Run
                                name: Run Tests
                                identifier: Run_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+Build_and_Publish.variables.node_version>
                                    command: npm test
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                                - "*.xml"
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+Build_and_Publish.variables.node_version>
                                    command: npm run build
                                    privileged: false
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheS3
                                name: Rebuild Cache
                                identifier: Rebuild_Cache
                                spec:
                                    connectorRef: mansongaws
                                    region: eu-west-2
                                    bucket: mansong-npm
                                    key: gesturerecognition
                                    sourcePaths:
                                        - node_modules
                                    archiveFormat: Tar
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Push Docker Image
                                identifier: Push_Docker_Image
                                spec:
                                    connectorRef: mansongdockerhub
                                    repo: mansong/gesturerecognition
                                    tags:
                                        - <+pipeline.sequenceId>
                                        - latest
                                    dockerfile: Dockerfile.prod
                                    context: ./
                                    optimize: true
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                          - step:
                                type: Run
                                name: Scan Docker Image
                                identifier: Scan_Docker_Image
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: bitnami/trivy:latest
                                    command: trivy image mansong/gesturerecognition:<+pipeline.sequenceId>
                                    privileged: false
              variables:
                  - name: node_version
                    type: String
                    value: node:16.5.0-alpine3.14
