pipeline:
    name: ElectronJS
    identifier: ElectronJS
    projectIdentifier: _mansong
    orgIdentifier: default
    description: A Simple Electron Project
    tags:
        electronjs: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: electron
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: Restore Cache from S3
                                identifier: Restore_Cache_from_S3
                                spec:
                                    connectorRef: mansongaws
                                    region: eu-west-2
                                    bucket: mansong-npm
                                    key: dependency-cache-{{ checksum "package.json" }}
                                    archiveFormat: Tar
                                when:
                                    stageStatus: Failure
                                failureStrategies: []
                          - step:
                                type: Run
                                name: Install Dependencies
                                identifier: Install_Dependencies
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: cimg/node:16.9.1-browsers
                                    command: sudo npm install
                                    privileged: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1.0"
                          - step:
                                type: Run
                                name: Lint
                                identifier: Lint
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: node:16.9.1
                                    command: npm run lint
                                    privileged: false
                          - step:
                                type: Run
                                name: Run Tests
                                identifier: Run_Test
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: electronuserland/builder:wine
                                    command: |-
                                        export DISPLAY=':99.0'
                                        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
                                        npm install
                                        npm test
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "*.xml"
                                    envVariables:
                                        JEST_JUNIT_OUTPUT_DIR: /tmp/test-reports/test.xml
                          - step:
                                type: SaveCacheS3
                                name: Save Cache to S3
                                identifier: Save_Cache_to_S3
                                spec:
                                    connectorRef: mansongaws
                                    region: eu-west-2
                                    bucket: mansong-npm
                                    key: dependency-cache-{{ checksum "package-lock.json" }}
                                    sourcePaths:
                                        - ./node_modules
                                    archiveFormat: Tar
              variables: []
