pipeline:
    name: Gotway
    identifier: Gotway
    projectIdentifier: _mansong
    orgIdentifier: default
    description: "Simple HTTP API Gateway powered with in-redis cache "
    tags:
        go: ""
        golang: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: gotway
                build: <+input>
                sslVerify: false
                prCloneStrategy: SourceBranch
    stages:
        - stage:
              name: CI
              identifier: CI
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Get Tags
                                identifier: Get_Version
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: bitnami/git
                                    command: |-
                                        git -c 'versionsort.suffix=-' \
                                            ls-remote --exit-code --refs --sort='version:refname' --tags <repository> '*.*.*' \
                                            | tail --lines=1 \
                                            | cut --delimiter='/' --fields=3

                                        export VERSION=`git describe --tags`
                                    privileged: false
                                    outputVariables:
                                        - name: VERSION
                                failureStrategies: []
                                when:
                                    stageStatus: Success
                          - parallel:
                                - step:
                                      type: Run
                                      name: DockerLint
                                      identifier: DockerLint
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: hadolint/hadolint:latest-alpine
                                          command: hadolint --ignore DL3018 Dockerfile
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Format
                                      identifier: Format
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: gofmt -s -w .
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Vet
                                      identifier: Vet
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: |-
                                              apk add build-base
                                              go vet ./...
                                          privileged: false
                                          resources:
                                              limits:
                                                  memory: 1Gi
                                                  cpu: "1"
                          - step:
                                type: Run
                                name: Clean
                                identifier: Clean
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.golangImage>
                                    command: |-
                                        rm -rf ./bin
                                        go clean
                                    privileged: false
                          - step:
                                type: Run
                                name: Build
                                identifier: Build2
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.golangImage>
                                    command: |-
                                        go build -tags netgo -a -v -ldflags -X main.version=<+execution.steps.Get_Version.output.outputVariables.VERSION> -s -w -o ./bin/gotway ./cmd/gotway/*.go
                                        chmod +x ./bin/*
                                    privileged: false
              variables:
                  - name: golangImage
                    type: String
                    value: golang:1.16.6-alpine3.14
