pipeline:
    name: Gotway
    identifier: Gotway
    projectIdentifier: _mansong
    orgIdentifier: default
    description: "Simple HTTP API Gateway powered with in-redis cache "
    tags:
        go: ""
        golang: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: gotway
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Run
                                      name: DockerLint
                                      identifier: DockerLint
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: hadolint/hadolint:latest-alpine
                                          command: hadolint --ignore DL3018 Dockerfile
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Format
                                      identifier: Format
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: make fmt
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Vet
                                      identifier: Vet
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: make vet
                                          privileged: false
              variables:
                  - name: golangImage
                    type: String
                    value: golang:1.16.6-alpine3.14
