pipeline:
    name: Gotway
    identifier: Gotway
    projectIdentifier: _mansong
    orgIdentifier: default
    description: "Simple HTTP API Gateway powered with in-redis cache "
    tags:
        go: ""
        golang: ""
        multi-arch: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: gotway
                build: <+input>
                sslVerify: false
                prCloneStrategy: SourceBranch
    stages:
        - stage:
              name: Build and Release
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: AutoBump
                                identifier: Get_Tags
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: quay.io/pantheon-public/autotag:v1.3.9
                                    command: |+
                                        # fetch all tags and history:
                                        git fetch --tags --unshallow --prune

                                        if [ $(git rev-parse --abbrev-ref HEAD) != "master" ]; then
                                          # ensure a local 'main' branch exists at 'refs/heads/main'
                                          git branch --track master origin/master
                                        fi

                                        export VERSION=`autotag --scheme=conventional`

                                        echo $PATH
                                        which autotag

                                    privileged: false
                                    outputVariables:
                                        - name: VERSION
                                failureStrategies: []
                                when:
                                    stageStatus: Success
                          - parallel:
                                - step:
                                      type: Run
                                      name: DockerLint
                                      identifier: DockerLint
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: hadolint/hadolint:latest-alpine
                                          command: hadolint --ignore DL3018 --ignore DL3007 Dockerfile
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Format
                                      identifier: Format
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: gofmt -s -w .
                                          privileged: false
                                - step:
                                      type: Run
                                      name: Vet
                                      identifier: Vet
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: <+CI.variables.golangImage>
                                          command: |-
                                              apk add build-base
                                              go vet ./...
                                          privileged: false
                                          resources:
                                              limits:
                                                  memory: 1Gi
                                                  cpu: "1"
                          - step:
                                type: Run
                                name: Snyk Scan
                                identifier: snyk_scan
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: snyk/snyk:golang-1.16
                                    command: SNYK_TOKEN=<+secrets.getValue("snykapitoken")> snyk test
                                    privileged: true
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1.0"
                          - step:
                                type: Run
                                name: Run Tests
                                identifier: Run_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: pricec/gotestsum
                                    command: gotestsum --junitfile results.xml --format standard-verbose -- -coverprofile=cover.out ./...
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "*.xml"
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1.0"
                          - step:
                                type: Run
                                name: Coverage Report
                                identifier: Coverage_Report
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.golangImage>
                                    command: |-
                                        go get github.com/axw/gocov/gocov
                                        go get github.com/AlekSi/gocov-xml

                                        gocov convert cover.out | gocov-xml > coverage.xml
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - coverage.xml
                          - step:
                                type: Run
                                name: Clean
                                identifier: Clean
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.golangImage>
                                    command: |-
                                        rm -rf ./bin
                                        go clean
                                    privileged: false
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.golangImage>
                                    command: |-
                                        export VERSION=<+execution.steps.Get_Tags.output.outputVariables.VERSION>

                                        go build -tags netgo -a -v -ldflags "-X main.version=${VERSION} -s -w" -o ./bin/gotway ./cmd/gotway/*.go
                                        chmod +x ./bin/*
                                    privileged: false
                                    envVariables:
                                        CGO_ENABLED: "0"
                                        GO111MODULE: "on"
                          - step:
                                type: Plugin
                                name: Build and Push Docker Image
                                identifier: Build_and_Push_Docker_Image
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: thegeeklab/drone-docker-buildx
                                    privileged: true
                                    settings:
                                        username: mansong
                                        password: <+secrets.getValue("mansongdockerhub")>
                                        platforms: linux/amd64,linux/arm64,linux/arm
                                        repo: mansong/gotway
                                        auto_tag: "true"
                                when:
                                    stageStatus: Success
                                failureStrategies: []
              variables:
                  - name: golangImage
                    type: String
                    value: golang:1.16.6-alpine3.14
    flowControl:
        barriers: []
