pipeline:
    name: BookStore
    identifier: Java
    projectIdentifier: _mansong
    orgIdentifier: default
    tags:
        java: ""
        maven: ""
        openjdk8: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: special-tribble
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Run
                                      name: CheckStyle
                                      identifier: CheckStyle
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                          command: mvn checkstyle:checkstyle
                                          privileged: false
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                - step:
                                      type: Run
                                      name: Compile
                                      identifier: Compile
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                          command: mvn clean compile
                                          privileged: false
                                          resources:
                                              limits:
                                                  memory: 1Gi
                                                  cpu: "1.0"
                          - step:
                                type: RunTests
                                name: Unit Tests
                                identifier: Unit_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    packages: org.springframework.boot,tn.devops.demo
                                    runOnlySelectedTests: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                          - step:
                                type: Run
                                name: Integration Tests
                                identifier: Integration_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                    command: mvn verify -Dsurefire.skip=true
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1.0"
                          - parallel:
                                - step:
                                      type: Run
                                      name: PMD
                                      identifier: PMD
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                          command: mvn pmd:pmd
                                          privileged: false
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                - step:
                                      type: Run
                                      name: Findbugs
                                      identifier: Findbugs
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                          command: mvn findbugs:findbugs
                                          privileged: false
                                          reports:
                                              type: JUnit
                                              spec:
                                                  paths:
                                                      - "**/*.xml"
                                      failureStrategies: []
                                - step:
                                      type: Run
                                      name: JavaDoc
                                      identifier: JavaDoc
                                      spec:
                                          connectorRef: mansongdockerhub
                                          image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                          command: mvn javadoc:javadoc
                                          privileged: false
              variables:
                  - name: mavenversion
                    type: String
                    value: 3.8.2
                  - name: javaversion
                    type: String
                    value: openjdk-8
                  - name: SONARQUBE_URL
                    type: String
                    value: "''"
                  - name: SONARQUBE_PORT
                    type: String
                    value: "9000"
    description: Book Store Java Application built using Maven.
