pipeline:
    name: PetClinic
    identifier: Java
    projectIdentifier: _mansong
    orgIdentifier: default
    tags:
        java: ""
        springboot: ""
        cosmos: ""
        spring: ""
        cosmosdb: ""
        spring-data-cosmosdb: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: spring-petclinic
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: CheckStyle
                                identifier: CheckStyle
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: <+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                    command: mvn checkstyle:checkstyle
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/target/checkstyle-result.xml"
              variables:
                  - name: mavenversion
                    type: String
                    value: 3.8.2
                  - name: javaversion
                    type: String
                    value: openjdk-8
    description: Petclinic is a Spring Boot application built using Maven.
