pipeline:
    name: Java
    identifier: Java
    projectIdentifier: _mansong
    orgIdentifier: default
    tags:
        java: ""
        springboot: ""
        cosmos: ""
        spring: ""
        cosmosdb: ""
        spring-data-cosmosdb: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: spring-petclinic
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                name: Run Tests
                                identifier: Run_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+CI.variables.mavenversion>-jdk-<+CI.variables.javaversion>
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    packages: com.
                                    runOnlySelectedTests: true
                                    preCommand: cd spring-petclinic
                          - step:
                                type: Run
                                name: Build
                                identifier: Build
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+pipeline.variables.mavenversion>-jdk-<+pipeline.variables.javaversion>
                                    command: mvn -B -DskipTests clean package
                                    privileged: false
              variables:
                  - name: mavenversion
                    type: String
                    value: 3.8.2
                  - name: javaversion
                    type: String
                    value: openjdk-8
