pipeline:
    name: Book Store
    identifier: Java
    projectIdentifier: _mansong
    orgIdentifier: default
    tags:
        java: ""
        maven: ""
        openjdk8: ""
    properties:
        ci:
            codebase:
                connectorRef: mansongGithub
                repoName: special-tribble
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.mansong_gke
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: CheckStyle
                                identifier: CheckStyle
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                    command: mvn checkstyle:checkstyle
                                    privileged: false
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/target/checkstyle-result.xml"
                          - step:
                                type: RunTests
                                name: Unit Tests
                                identifier: Unit_Tests
                                spec:
                                    connectorRef: mansongdockerhub
                                    image: maven:<+CI.variables.mavenversion>-<+CI.variables.javaversion>
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    packages: tn.devops.demo
                                    runOnlySelectedTests: true
              variables:
                  - name: mavenversion
                    type: String
                    value: 3.8.2
                  - name: javaversion
                    type: String
                    value: openjdk-8
    description: Book Store Java Application built using Maven.
